name: "build"
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:  # 添加这行以启用手动触发

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Assemble
        run: ./gradlew assemble --scan

      - name: Test Video
        run: ./gradlew test --tests "xyz.cssxsh.bilibili.VideoTest" --scan --info

      - name: Test Season
        run: ./gradlew test --tests "xyz.cssxsh.bilibili.SeasonTest" --scan --info

      - name: Test Search
        run: ./gradlew test --tests "xyz.cssxsh.bilibili.SearchTest" --scan --info

      - name: BuildPlugin
        run: ./gradlew buildPlugin

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/mirai/*
